# Numpy
Numerical Python 의 약자로 과학 및 공학 분야에서 사용되는 오픈소스 파이썬 라이브러리

- 대량의 데이터를 다루는 **배열을 만들어주는 라이브러리**
- 파이썬 배열(리스트)와 다르게 **수학적인 행렬의 사칙연산을 수행**해줌

In [1]:
# 설치..
#pip install numpy

### 1. 일반적인 파이썬 배열(리스트)

In [2]:
aaa= [10,20,30]
bbb= [4,5,6]

print(aaa)
print(bbb)

[10, 20, 30]
[4, 5, 6]


In [3]:
#파이썬 리스트의 덧셈을 하면...수학계산이 아니라 결합연산
ccc= aaa + bbb
print(ccc)

[10, 20, 30, 4, 5, 6]


In [4]:
#자료형 확인
print( type(aaa) )

<class 'list'>


### 2. numpy 배열

In [5]:
import numpy as np

aa= np.array([10,20,30])
bb= np.array([4,5,6])

print(aa)
print(bb)

[10 20 30]
[4 5 6]


In [6]:
# 배열의 사칙연산이 수학적으로 수행됨
cc= aa + bb
print(cc)

[14 25 36]


In [7]:
# 배열의 요소 개수 확인
print(len(aa))
print(len(bb))
print(len(cc))

3
3
3


In [8]:
# 단, 넘파이 배열을 사용할때는 가급적 사이즈를 .shape 속성으로 확인하는 것을 권장
print(aa.shape)
print(bb.shape)
print(cc.shape) #튜플로 (행,열) 개수를 표시... 단, 현재 1차원이니..값이 하나만..

(3,)
(3,)
(3,)


In [9]:
#자료형 확인
print( type(aa) )

<class 'numpy.ndarray'>


### 3. 다차원 넘파이 배열

In [14]:
aaaa= np.array([ [10,20,30,40], [5,6,7,8] ])
print( len(aaaa) ) #2 <--행개수
print( aaaa.shape ) #튜플 (행,열)


bbbb= np.array([ [100,200,300,400],[50,60,70,80] ])
print( bbbb.shape )

#사칙연산 가능
cccc= aaaa + bbbb
print( cccc.shape )
print( cccc )

2
(2, 4)
(2, 4)
(2, 4)
[[110 220 330 440]
 [ 55  66  77  88]]


In [15]:
#사칙연산 모두 가능
print( aaaa - bbbb )
print( aaaa * bbbb ) #요소별 곱셈
print( aaaa / bbbb ) #요소별 나눗셈

[[ -90 -180 -270 -360]
 [ -45  -54  -63  -72]]
[[ 1000  4000  9000 16000]
 [  250   360   490   640]]
[[0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]]


In [16]:
# 연산 주의1 행렬의 개수가 다르면 에러!!!
dddd= np.array([10,20,30,40], [500,600])

TypeError: Field elements must be 2- or 3-tuples, got '500'

In [18]:
# 연산하는 행렬의 개수도 맞아야 함.
eeee= np.array([ [10,20], [50,60] ])

ffff= aaaa + eeee

ValueError: operands could not be broadcast together with shapes (2,4) (2,2) 

In [19]:
# 수학적 행렬의 곱셈 - 1차원 배열일때는 내적 곱(dot), 2차원 배열일 떄는 수학의 행렬 곱셈을 수행

#2차원 배열
A= np.array([
    [1,2],
    [3,4]
])
B= np.array([
    [5,6],
    [7,8]
])
print( A @ B ) #행렬 곱
#or
print( np.matmul(A,B) ) 

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [20]:
# 1차원 배열일 경우에는 내적곱(요소끼리 곱하여 덧셈 ) -- 벡터 내적 --> 스칼라값
C= np.array([1,2,3,4]) #벡터
D= np.array([5,6,7,8]) #벡터
print( np.dot(C,D) ) #스칼라

70


### 4. 넘파이 주요메소드 와 속성

In [21]:
#1. 특정 규칙을 가진 값들로 배열을 생성해주는 기능메소드
aaa= np.zeros(5)
print(aaa)

[0. 0. 0. 0. 0.]


In [22]:
bbb= np.ones(5)
print(bbb)

[1. 1. 1. 1. 1.]


In [23]:
ccc= np.full(5, 7) #7로 5개...
print(ccc)

[7 7 7 7 7]


In [24]:
ddd= np.arange(5) #0~4
print(ddd)

[0 1 2 3 4]


In [25]:
eee= np.arange(2,20,3) #start, <end, step
print(eee)

[ 2  5  8 11 14 17]


In [26]:
fff= np.random.random(3) #랜덤값 3개 ( 0.0 ~ 1.0 )
print(fff)

[0.30160101 0.29992291 0.43624551]


In [27]:
ggg= np.linspace(0, 100, 3) # 0부터 100까지의 범위안에서 균등 3분할 지점 값들
print(ggg)

[  0.  50. 100.]


In [29]:
#2. 배열 속성 및 정보

# 배열의 행,열 크기정보
aaa= np.array([10,20,30]) #1차원
print(aaa.shape)

bbb= np.array([ [1,2,3], [4,5,6] ]) #2차원
print(bbb.shape)

(3,)
(2, 3)


In [30]:
#요소의 총 개수
print(aaa.size)
print(bbb.size)

3
6


In [32]:
#파이썬의 len()함수는 차원 상관없이 요소의 개수
print(len(aaa))
print(len(bbb)) #2행 <--행개수

#행개수를 확인하는 또 다른 방법
print( bbb.shape[0] )

3
2
2


In [34]:
# 배열의 원소의 자료형
print(aaa.dtype)
print(bbb.dtype)

print( type(aaa) )
print( type(bbb) )

int64
int64
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [35]:
ccc= np.array([3.14, 4.5, 7.89])
print(ccc.dtype)

float64


In [38]:
ddd= np.array(['sam','robin','hong'])
print(ddd.dtype)

<U5


In [41]:
# 배열을 만들때 자료형을 지정할 수도 있음.. 다른 데이터 저장은 안됨.
eee= np.array(['sam','robin','hong'], dtype=str) #dtype=int 를 사용하면 에러!

In [43]:
# 넘파이 배열을 기본적으로 같은 자료형만 저장 가능하지만...다른 자료형을 함께 저장하면...전부 문자열 타입이 됨.
fff= np.array([10,20,30, 3.14, True, 'sam'])
print(fff.dtype)

<U32


In [44]:
fff[0] + 3

TypeError: can only concatenate str (not "int") to str

In [45]:
# 배열의 차원 정보 확인
aa= np.array(12)  #스칼라 (0차원 배열)
aa.ndim

0

In [48]:
bb= np.array([1,3,5])  #벡터 (1차원 배열)
bb.ndim

1

In [49]:
cc= np.array([ [2,6,4], [1,3,5] ]) #매트릭스(행렬) -2차원 배열
cc.ndim

2

In [50]:
dd= np.array([
    [ [2,6,4], [1,3,5] ],
    [ [2,6,4], [1,3,5] ]
]) #3차원 배열 ( 텐서 Tensor )
dd.ndim

3

In [51]:
# 수학 및 통계 연산 기능 메소드(함수)

#10명의 학생 성적 데이터
scores= np.array([70,80,98,26,84,100,65,53,38,85])

In [52]:
# 요소들의 총합 구하기 [2가지 방법]
print('총점:', scores.sum() )
print('총점:', np.sum(scores) )

총점: 699
총점: 699


In [53]:
# 요소들의 평균 구하기 [2가지 방법]
print('평균:', scores.mean() )
print('평균:', np.mean(scores) )

평균: 69.9
평균: 69.9


In [54]:
# 요소의 최대값/최소값 구하기 [2가지 방법]
print('최대값:', scores.max() )
print('최대값:', np.max(scores) )
print('최소값:', scores.min() )
print('최소값:', np.min(scores) )

최대값: 100
최대값: 100
최소값: 26
최소값: 26


In [55]:
# 조건에 따라 원소들의 결과값을 계산하는 기능(파이썬 삼항연산자+반복문)
#예) 60점 이상은 'pass' 아니면 'fail'
result= np.where( scores > 60 , 'pass', 'fail' ) #조건, 참일때 값, 거짓일때 값
print(result)

['pass' 'pass' 'pass' 'fail' 'pass' 'pass' 'pass' 'fail' 'fail' 'pass']


In [56]:
# 배열 결합 (파이썬의 리스트처럼)
aaa= np.array([1,2,3])
bbb= np.array([4,5,6])

result= np.concatenate( (aaa,bbb) ) #튜플로 
print(result)

[1 2 3 4 5 6]


In [59]:
# 2차원 배열일때는.. 행으로 붙일지..열로 붙일지..
a= np.array([[1,2],
             [3,4]])

b= np.array([[5,6],
             [7,8]])

In [61]:
#행 기준 연결 (위아래)
result1= np.concatenate( (a,b), axis=0 ) # axis=0 행방향..으로 내려가면서 붙이기
print(result1)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [62]:
#열 기준 연결 (좌우)
result2= np.concatenate( (a,b), axis=1 ) # axis=1 열방향..으로 오른쪽으로 가면서 붙이기
print(result2)

[[1 2 5 6]
 [3 4 7 8]]


In [63]:
# 인덱싱 및 슬라이싱

#1번학생(0번 인덱싱)의 성적데이터
first_student= scores[0]

#3~7번 학생(슬라이싱) [인덱스 번호로는 2~6]
middle_student= scores[2:7]

print(first_student)
print(middle_student)

70
[ 98  26  84 100  65]


In [67]:
# 불리언 인덱싱 - 기준 점수 이상인 학생만 추출
# 80점 이상인 학생들의 성적만 추출
high_scores= scores[ scores>=80 ] #조건값이 true인 요소들만 인덱싱
print(high_scores)
print(high_scores.mean())
print(len(high_scores))

[ 80  98  84 100  85]
89.4
5


In [69]:
#배열의 차원을 변경 시켜주는 기능 reshape()
# 1차원 → 2차원 (reshape)
# 5명 학생 × 7일 = 35개 점수
scores_1d = np.array([
    80, 75, 90, 85, 87, 92, 78,
    70, 65, 75, 80, 82, 85, 79,
    90, 88, 91, 94, 96, 95, 93,
    60, 65, 70, 72, 74, 76, 78,
    85, 87, 88, 90, 92, 91, 89
])
print(scores_1d)

[80 75 90 85 87 92 78 70 65 75 80 82 85 79 90 88 91 94 96 95 93 60 65 70
 72 74 76 78 85 87 88 90 92 91 89]


In [70]:
#학생수, 날짜수) 형태로 변경
scores_2d= scores_1d.reshape(5,7) #5행 7열로 만들어 줘.
print(scores_2d)

[[80 75 90 85 87 92 78]
 [70 65 75 80 82 85 79]
 [90 88 91 94 96 95 93]
 [60 65 70 72 74 76 78]
 [85 87 88 90 92 91 89]]


In [71]:
# 행,열중 한쪽만 지정하고..나머지는 알아서 계산되도록 설정
scores_2d= scores_1d.reshape(5,-1) #5행 ?열로 만들어 줘.
print(scores_2d)

[[80 75 90 85 87 92 78]
 [70 65 75 80 82 85 79]
 [90 88 91 94 96 95 93]
 [60 65 70 72 74 76 78]
 [85 87 88 90 92 91 89]]


In [72]:
# 행,열중 한쪽만 지정하고..나머지는 알아서 계산되도록 설정
scores_2d= scores_1d.reshape(4,-1) #4행 ?열로 만들어 줘.
print(scores_2d)

ValueError: cannot reshape array of size 35 into shape (4,newaxis)

In [73]:
# 행,열중 한쪽만 지정하고..나머지는 알아서 계산되도록 설정
scores_2d= scores_1d.reshape(-1,7) #?행 7열로 만들어 줘.
print(scores_2d)

[[80 75 90 85 87 92 78]
 [70 65 75 80 82 85 79]
 [90 88 91 94 96 95 93]
 [60 65 70 72 74 76 78]
 [85 87 88 90 92 91 89]]


In [79]:
# 차원을 변환하면, 좋은점.. 분석하기 용이해짐

# 학생별 평균 점수 
student_aver= scores_2d.mean(axis=1) #행기준 계산 -- 옆으로 가면서 계산
print(student_aver, len(student_aver))

# 날짜별 평균 점수
day_aver= scores_2d.mean(axis=0) #열기준 계산 -- 아래로 가면서 계산
print(day_aver, len(day_aver))

[83.85714286 76.57142857 92.42857143 70.71428571 88.85714286] 5
[77.  76.  82.8 84.2 86.2 87.8 83.4] 7
